- name: HDFS Format NameNode 
  become: yes
  become_user: hdfs
  become_flags: "-i"
  command: /opt/hadoop/bin/hdfs namenode -format -force
  when: format_hdfs

- name: HDFS Start
  become: yes
  become_user: hdfs
  become_flags: "-i"
  command: /opt/hadoop/sbin/start-dfs.sh
  when: start_hdfs

- name: HDFS Stop
  become: yes
  become_user: hdfs
  become_flags: "-i"
  command: /opt/hadoop/sbin/stop-dfs.sh
  when: stop_hdfs
