- name: Install requierments (1)
  apt:
    name:
      - python3
      - python3-dev
      - python3-pip
      - git
      - curl
      - nodejs
      - npm
    state: present

- name: Install JupyterHub
  shell: curl -L https://tljh.jupyter.org/bootstrap.py | sudo -E python3 - --admin admin

- name: Install JupyterLab
  pip:
    name: jupyterlab
    executable: /opt/tljh/hub/bin/pip

- name: Make config directory
  file:
    path: /etc/jupyterhub
    state: directory

- name: Install Yarn Spawner
  pip:
    name: jupyterhub-yarnspawner
    executable: /opt/tljh/hub/bin/pip

- name: Install Configurable HTTP Proxy
  command: npm install -g configurable-http-proxy

- name: Copy config file
  template:
    src: jupyterhub_config.py.j2
    dest: /etc/jupyterhub/jupyterhub_config.py

- name: Copy keytab files
  copy:
    src: "jupyterhub.keytab"
    dest: "/etc/jupyterhub/jupyterhub.keytab"

- name: Add Kerberos config to Spark
  blockinfile:
    path: /opt/spark/conf/spark-defaults.conf
    block: |
      spark.kerberos.keytab       /etc/jupyterhub/jupyterhub.keytab
      spark.kerberos.principal    jupyterhub@HOME
