# Download and install JDK 8 for Hadoop
# Set this JAVA_HOME later in Hadoop enviroment config file (hadoop-env.sh)

- name: Download JDK archive file
  get_url:
    url: "{{ jdk_url }}"
    dest: "/tmp/{{ jdk_archive }}"

- name: Unarchive the file
  ansible.builtin.unarchive:
    src: "/tmp/{{ jdk_archive }}"
    dest: "/opt/"
    creates: "/opt/{{ jdk_archive | replace('.tar.gz', '') }}"
    remote_src: yes

- name: Set JAVA_HOME fact
  set_fact:
    java_home: "/opt/{{ jdk_archive | replace('.tar.gz', '') }}"

- name: Rmove unarchive file
  file:
    path: "/tmp/{{ jdk_archive }}"
    state: absent
