- name: Copy Java 8 to the server
  copy:
    src: "{{ jdk_archive }}"
    dest: "/tmp/{{ jdk_archive }}"
    force: no

- name: Unarchive the file
  ansible.builtin.unarchive:
    src: "/tmp/{{ jdk_archive }}"
    dest: "/opt/"
    creates: "/opt/{{ jdk_directory }}"
    remote_src: yes

- name: Set Java 8 as the default
  alternatives:
    name: java
    link: "/usr/bin/java"
    path: "/opt/{{ jdk_directory }}/bin/java"
    priority: 1000

- name: Set JAVA_HOME environment variable
  template:
    src: jdk.sh.j2
    dest: /etc/profile.d/jdk.sh
    mode: '0755'
